version: '3.8'

services:
  app-cli:
    build: .
    container_name: cnpj-etl-app
    restart: on-failure
    environment:
      - MONGO_URI=${MONGO_URI}
      - BASE_URL=https://dados-abertos-rf-cnpj.casadosdados.com.br/arquivos/
      - NODE_OPTIONS=--max-old-space-size=4096
    volumes:
      - ./data:/app/data
    depends_on:
      - mongo

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: cnpj-etl-api
    restart: unless-stopped
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: cnpj-etl-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: 
      - --wiredTigerCacheSizeGB=1.5

volumes:
  mongo_data: