services:
  app-cli:
    build: .
    command: ["node", "src/index.js"]
    environment:
      - BASE_URL=https://dados-abertos-rf-cnpj.casadosdados.com.br/arquivos/
      - MONGO_URI=${MONGO_URI}
      - NODE_OPTIONS="--max-old-space-size=4096" 
    volumes:
      - ./data:/app/data
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    command: ["--wiredTigerCacheSizeGB", "1.5"]

volumes:
  mongo_data: